# Introduction to Numpy

NumPy  provides us with blistering fast and efficient, list-like, data types called N-Dimensional Arrays or ndarrays or more simply arrays. This list-like data type is effectively a lighter weight version of a Python list, as it uses less of your computer's memory, which makes it more efficient, especially when dealing with large datasets

In [7]:
import numpy as np

numpy_arry = np.array([range(0,10)])
numpy_arry
type(numpy_arry)

#multidimentional arrays
numpy_ndarr = np.array([[1,2,3,4],[1,2,3,4]])
numpy_ndarr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

### Performing Array operation

In [9]:
list_of_integers = [0,1,2,3,4]

array_of_integers = np.array(list_of_integers)

array_of_integers + 3

array([3, 4, 5, 6, 7])

In [10]:
lengths_of_each_room = np.array([10,12,20,5])
widths_of_each_room = np.array([13,15,16,4])
areas_of_each_room = lengths_of_each_room * widths_of_each_room

print("Here is the array with the square footages for each room",areas_of_each_room)

Here is the array with the square footages for each room [130 180 320  20]


In [25]:
x = np.array([1,2,3,4])
print(type(x))

#Scalr Math using arrays
x = np.add(x,1)
x = np.subtract(x,2)
x = np.multiply(x,3)
x = np.divide(x,3)
x = np.power(x,2)
x

<class 'numpy.ndarray'>


array([0., 1., 4., 9.])

## Measures of central tendancy

In [ ]:
40650 , 40812 ,41300,41450,39594,40734,39993,38814,37828,35716

## Covariance and Corelation